In [13]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from util1 import Cost_Function, Gradient_Descent, Cost_Function_Derivative, Cost_Function, Prediction, Sigmoid
from dataTrans import download_data,transtonumber,rescaleNormalization
from sklearn import svm
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, recall_score, precision_score, accuracy_score



#% step-1: load data and divide it into two subsets, used for training and testing
data = download_data('car.csv',[0,1,2,3,4,5,6])
colnames = ['buying','maint','doors','persons','lug_boot','safety','class']
print(data)

### define the transformation notation 
buying = ['low','med','high','vhigh']
        # low = 0, med = 1, high = 2, vhigh = 3
maint = ['low','med','high','vhigh']
        # low = 0, med = 1, high = 2, vhigh = 3
doors = ['2', '3', '4', '5more']
        # 2 = 0, 3 = 1, 4 = 2, 5more = 3
persons = ['2', '4', 'more']
        # 2 = 0, 4 = 1, more = 2
boot = ['small','med', 'big']
        # samll = 0, med = 1, big = 2
safety = ['low', 'med','high']
        # low = 0, med = 1, high = 2
names = [buying,maint,doors,persons,boot,safety]

### transform
car1 = np.transpose(np.zeros(np.shape(car)))
for i in range(6):
    car1[i] = transtonumber(car[i],names[i])
# Nomoralization 
#X = np.transpose(rescaleNormalization(car1))
X = np.transpose(car1)


## transform Y to 0 & 1 
y = np.zeros(np.shape(car[6]))
for i in range(len(car[6])):
    if data[6][i] != 'unacc':
        y[i] = 1

print(X)

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
5     vhigh  vhigh      2     2    med  high  unacc
6     vhigh  vhigh      2     2    big   low  unacc
7     vhigh  vhigh      2     2    big   med  unacc
8     vhigh  vhigh      2     2    big  high  unacc
9     vhigh  vhigh      2     4  small   low  unacc
10    vhigh  vhigh      2     4  small   med  unacc
11    vhigh  vhigh      2     4  small  high  unacc
12    vhigh  vhigh      2     4    med   low  unacc
13    vhigh  vhigh      2     4    med   med  unacc
14    vhigh  vhigh      2     4    med  high  unacc
15    vhigh  vhigh      2     4    big   low  unacc
16    vhigh  vhigh      2     4    big   med  unacc
17    vhigh  vhigh      2     4    big  high  unacc
18    vhigh 

In [14]:
# number of training samples


trainX,testX,trainY,testY = train_test_split(X,y,test_size=0.33)

# check properties of data
print(testY)
print(testX)
print(len(trainX))
print(len(trainY))
print(len(testX))
print(len(testY))

[0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1.
 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0.
 0. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1.
 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 1. 1. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 1.
 0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 1.
 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 1.

In [15]:
#SK learn method

clf = LogisticRegression()
# call the function fit() to train the class instance
clf.fit(trainX,trainY)
# accuracy for sklearn
scikit_score = clf.score(testX,testY)


#prediction with sklearn
predSK = clf.predict(testX)

# evaluation
testYDiff1 = np.abs(predSK - testY)
avgErr1 = np.mean(testYDiff1)
stdErr1 = np.std(testYDiff1)

print("Score SK:", scikit_score)
print("Avg Error SK:", avgErr1)
print("Std Error SK:", stdErr1)

#confusion matrix
print("SK Learn Confusion Matrix:")
print(confusion_matrix(testY,predSK))
print("accuracy:",accuracy_score(testY,predSK))
print("precision:",precision_score(testY,predSK))
print("recall:",recall_score(testY,predSK))

Score SK: 0.8651488616462347
Avg Error SK: 0.13485113835376533
Std Error SK: 0.34156450172472397
SK Learn Confusion Matrix:
[[373  35]
 [ 42 121]]
accuracy: 0.8651488616462347
precision: 0.7756410256410257
recall: 0.7423312883435583


In [16]:
# fitting SVM model


svm = svm.SVC(C = 1000, kernel = "linear")
svm.fit(trainX, trainY)
svm_score = svm.score(testX,testY)

#prediction with svm
predSVM = svm.predict(testX) 

# evaluation
svmDiff = np.abs(predSVM - testY)
svm_avgErr = np.mean(svmDiff)
svm_stdErr = np.std(svmDiff)

print("Score SVM:", svm_score)
print("Avg Error SVM:", svm_avgErr)
print("Std Error SVM:", svm_stdErr)

#confusion matrix
print("SVM Learn Confusion Matrix:")
print(confusion_matrix(testY,predSK))
print("accuracy:",accuracy_score(testY,predSVM))
print("precision:",precision_score(testY,predSVM))
print("recall:",recall_score(testY,predSVM))

Score SVM: 0.8633975481611208
Avg Error SVM: 0.13660245183887915
Std Error SVM: 0.34342717130490114
SVM Learn Confusion Matrix:
[[373  35]
 [ 42 121]]
accuracy: 0.8633975481611208
precision: 0.7741935483870968
recall: 0.7361963190184049


In [17]:
# fitting random forest model


rf = RandomForestClassifier(n_estimators=20, random_state=0)  
rf.fit(trainX, trainY) 
rf_score = rf.score(testX,testY)

#prediction with rf
predRF = rf.predict(testX) 

# error of random forest
rfDiff = np.abs(predRF - testY)
rf_avgErr = np.mean(rfDiff)
rf_stdErr = np.std(rfDiff)

print("Score RF:", rf_score)
print("Avg Error RF:", rf_avgErr)
print("Std Error RF:", rf_stdErr)

#confusion matrix
print("RF Learn Confusion Matrix:")
print(confusion_matrix(testY,predRF))
print("accuracy:",accuracy_score(testY,predRF))
print("precision:",precision_score(testY,predRF))
print("recall:",recall_score(testY,predRF))

Score RF: 0.9824868651488616
Avg Error RF: 0.017513134851138354
Std Error RF: 0.1311732631248617
RF Learn Confusion Matrix:
[[403   5]
 [  5 158]]
accuracy: 0.9824868651488616
precision: 0.9693251533742331
recall: 0.9693251533742331


In [18]:
#gradient descent method

theta = [0,0,0,0,0,0] #initial model parameters
alpha = 0.1 # learning rates
max_iteration = 1000 # maximal iterations

m = len(y) # number of samples

for x in range(max_iteration):
        # call the functions for gradient descent method
        new_theta = Gradient_Descent(X,y,theta,m,alpha)
        theta = new_theta
        if x % 200 == 0:
            # calculate the cost function with the present theta
            Cost_Function(X,y,theta,m)
            
#get score for gradient descent method 
score = 0
length = len(testX)
for i in range(length):
        prediction = round(Prediction(theta,testX[i]))
        answer = testY[i]
        if prediction == answer:
            score += 1

GD_score = float(score) / float(length)
            
#prediction with gradient descent method
predGD = [Prediction(theta,i) for i in testX]
predGD = [float(int(j>=.6)) for j in predGD]

#evaluation
testDiff = np.abs(predGD - testY)
avgErr = np.mean(testDiff)
stdErr = np.std(testDiff)

print("Score GD:", GD_score)
print("Avg Error GD:", avgErr)
print("Std Error GD:", stdErr)

#confusion matrix
print("GD Learn Confusion Matrix:")
print(confusion_matrix(testY,predGD))
print("accuracy:",accuracy_score(testY,predGD))
print("precision:",precision_score(testY,predGD))
print("recall:",recall_score(testY,predGD))

Score GD: 0.8143607705779334
Avg Error GD: 0.18563922942206654
Std Error GD: 0.388815259373456
GD Learn Confusion Matrix:
[[367  41]
 [ 65  98]]
accuracy: 0.8143607705779334
precision: 0.7050359712230215
recall: 0.6012269938650306


In [19]:
# comparing different Methods
SK_score = clf.score(testX,testY)
SVM_score = svm.score(testX,testY)
RF_score = rf.score(testX,testY)
GD_score = float(score) / float(length)

if (SVM_score > RF_score) & (SVM_score > SK_score) & (SVM_score > GD_score):
    print ('SVM method won!') 
if (SK_score > RF_score) & (SK_score > SVM_score) & (SK_score > GD_score): 
    print ('SK method won!') 
if (RF_score > SK_score) & (RF_score > SVM_score) & (RF_score > GD_score): 
    print ('RF method won!')
if (GD_score > SK_score) & (GD_score > SVM_score) & (GD_score > RF_score): 
    print ('GD method won!')
print("SK score:",SK_score)
print("SVM score:",SVM_score)
print("RF score:",RF_score)
print("GD score:",GD_score)



RF method won!
SK score: 0.8651488616462347
SVM score: 0.8633975481611208
RF score: 0.9824868651488616
GD score: 0.8143607705779334
